# Find all the available rules by running:
# Pods/SwiftLint/swiftlint rules

included:
- ../SwiftImageEffects

excluded:
- Carthage
- Pods

disabled_rules:
  - line_length
  - file_length
  - force_cast
  - force_try
  - comma
  - trailing_comma

opt_in_rules:
#performance:
  - empty_count
  - first_where
#lint:
  - overridden_super_call
  - prohibited_super_call
#idiomatic:
  - redundant_nil_coalescing
  - fatal_error_message
  - nimble_operator
  - no_extension_access_modifier
#style:
  - operator_usage_whitespace
  - number_separator
  - switch_case_on_newline
  - closure_spacing
  - conditional_returns_on_newline
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

vertical_whitespace:
 max_empty_lines: 2
trailing_whitespace:
 ignores_empty_lines: true
 ignores_comments: true
