use_frameworks!

target 'SwiftImageEffects_Example' do
  platform :ios, '8.1'

  # core
  pod 'SwiftImageEffects', :path => '../'

  # experimental
  pod 'SwiftImageEffects/UIVisualEffect', :path => '../'

  # samples
  pod 'SwiftImageEffectsSamples', :git => 'https://github.com/Coeur/ImageEffectsSamples'

  # best practices
  # (SwiftLint 0.28.2 needs Swift 4.2)
  pod 'SwiftLint', '~> 0.28.1.0'

  target 'SwiftImageEffects_Tests' do
    inherit! :search_paths
  end
end
