# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

matrix:
  include:
    - osx_image: xcode9
      env: SDK=iphonesimulator11.0
      
    - osx_image: xcode9
      env: SDK=iphonesimulator10.3.1
      
    - osx_image: xcode8.3
      env: SDK=iphonesimulator9.3
      
    - osx_image: xcode7.3
      env: SDK=iphonesimulator8.4

language: swift
cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/SwiftImageEffects.xcworkspace -scheme SwiftImageEffects-Example -sdk $SDK ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
